//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIeldDataAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class gather_points_measurements
    {
        public int gather_points_measurement_id { get; set; }
        public System.DateTime measure_date { get; set; }
        public float Pcoef { get; set; }
        public float Tcoef { get; set; }
        public float Pf { get; set; }
        public float Tf { get; set; }
        public int gather_point_id { get; set; }
        public int final_gather_points_measurements_id { get; set; }
    
        public virtual gather_points gather_points { get; set; }
        public virtual final_gather_point_measurements final_gather_point_measurements { get; set; }
    }
}
