//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIeldDataAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class gather_points
    {
        public gather_points()
        {
            this.wells = new HashSet<well>();
            this.gather_points_measurements = new HashSet<gather_points_measurements>();
            this.pipes = new HashSet<pipe>();
            this.pipes1 = new HashSet<pipe>();
            this.gather_points1 = new HashSet<gather_points>();
        }
    
        public int gather_point_id { get; set; }
        public string name { get; set; }
        public Nullable<int> next_gather_point_id { get; set; }
    
        public virtual ICollection<well> wells { get; set; }
        public virtual ICollection<gather_points_measurements> gather_points_measurements { get; set; }
        public virtual ICollection<pipe> pipes { get; set; }
        public virtual ICollection<pipe> pipes1 { get; set; }
        public virtual ICollection<gather_points> gather_points1 { get; set; }
        public virtual gather_points gather_points2 { get; set; }
    }
}
