//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIeldDataAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class shtutzer
    {
        public int shtutzer_id { get; set; }
        public int well_id { get; set; }
        public float d1 { get; set; }
        public float d2 { get; set; }
        public float d_sht_current { get; set; }
        public float M { get; set; }
        public float ro { get; set; }
        public float ro_g { get; set; }
        public float ro_l { get; set; }
        public float k { get; set; }
        public float C_l { get; set; }
        public float z { get; set; }
        public float D { get; set; }
    
        public virtual well well { get; set; }
    }
}
