//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIeldDataAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class wells_measurements
    {
        public int measurement_id { get; set; }
        public int well_id { get; set; }
        public System.DateTime measure_date { get; set; }
        public float gas_output { get; set; }
        public float cond_output { get; set; }
        public float wellhead_P { get; set; }
        public float wellhead_T { get; set; }
        public float inlet_P { get; set; }
        public float inlet_T { get; set; }
    
        public virtual well well { get; set; }
    }
}
